/* supervisor_fw.h - SAFETY SUPERVISOR (STM32G030F6P6TR)
 *
 * Physically drives FORCE_PT and GATE_ENABLE. Final authority on boost.
 *
 * FAULT_OUT CORRECTION: per signal_flow_all_scenarios.html, FAULT_OUT is
 * generated by the Output Monitor (LM393 comparator) entirely in
 * hardware and is an INPUT to this chip (PB0 per your scenario doc) -
 * not something this firmware drives. Modeled below as a snapshot field
 * the caller reads off the physical pin, same as main_adc/sub_adc.
 *
 * Kept as a continuously-re-evaluated decision each cycle rather than a
 * stateful machine - an independent safety channel is safer as a small
 * "recompute from scratch every time" than something with its own
 * states to fall out of sync in.
 *
 * Per schematic, this MCU has its OWN MAIN_ADC/SUB_ADC taps (input-side
 * validity) and its own HEARTBEAT input pin from the main MCU - both
 * read directly, not via UART.
 */
#ifndef SUPERVISOR_FW_H
#define SUPERVISOR_FW_H

#include <stdint.h>
#include <stdbool.h>
#include "fault_codes.h"
#include "shared_protocol.h"

/* PLACEHOLDER tunables - independently chosen, not shared with main MCU's. */
#define SUP_ADC_MIN_VALID_COUNTS   620u
#define SUP_ADC_MAX_VALID_COUNTS   3410u
#define SUP_ADC_EXPECTED_SUM       4095u
#define SUP_ADC_SUM_TOLERANCE      100u

#define SUP_HEARTBEAT_TIMEOUT_MS   150u  /* PLACEHOLDER */

/* Consecutive-failure debounce, independently chosen from the main
 * MCU's FAULT_DEBOUNCE_SAMPLES - absorbs single-sample ADC noise on
 * THIS chip's own independent check, per the confirmed transient-fault
 * definition. PLACEHOLDER. */
#define SUP_FAULT_DEBOUNCE_SAMPLES 3u

typedef struct {
    uint16_t main_adc;
    uint16_t sub_adc;
    bool     heartbeat_pin_state;   /* raw read of HEARTBEAT input pin */
    bool     fault_out_asserted;    /* raw read of FAULT_OUT input pin from
                                      * the LM393 output monitor - true means
                                      * the hardware comparator sees a
                                      * MAIN_OUT/SUB_OUT problem, independent
                                      * of any firmware check */
    uint32_t now_ms;
} sup_snapshot_t;

typedef struct {
    bool     last_heartbeat_pin_state;
    uint32_t last_heartbeat_change_ms;

    uint8_t  last_rx_seq;
    bool     have_valid_request;
    bool     req_want_boost;
    uint32_t last_valid_rx_ms;

    uint8_t  input_fail_streak; /* debounce for own MAIN_ADC/SUB_ADC checks */

    fault_code_t current_fault;
    bool         gate_state;
} sup_context_t;

void sup_init(sup_context_t *ctx, uint32_t now_ms);
void sup_run(sup_context_t *ctx, const sup_snapshot_t *snap);

#endif /* SUPERVISOR_FW_H */
